In [1]:
# 신경망을 효율적으로 구현하기 위해 numpy의 다차원 배열을 이용한 계산법을 공부해보자.

In [2]:
import numpy as np
A = np.array([1,2,3,4])

print(A)
print(np.ndim(A)) # A의 차원 수
print(A.shape) # 배열의 형상 (튜플로 반환)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [4]:
B = np.array([[1,2],[3,4],[5,6]])

print(B)
print(np.ndim(B))
print(B.shape) # 3행 2열

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [5]:
A = np.array([[1,2],[3,4]])

print(A.shape)

B = np.array([[5,6],[7,8]])

print(B.shape)

np.dot(A,B) # 두 행렬을 곱하는 함수 dot. 입력이 1차원 배열이면 벡터를, 2차원 배열이면 행렬 곱을 계산한다.

(2, 2)
(2, 2)


array([[19, 22],
       [43, 50]])

In [6]:
A = np.array([[1,2,3],[4,5,6]])

print(A.shape)

B = np.array([[1,2],[3,4],[5,6]])

print(B.shape)

np.dot(A,B) # A의 열 수 = B의 행 수 여야 계산할 수 있다.

(2, 3)
(3, 2)


array([[22, 28],
       [49, 64]])

In [7]:
C = np.array([[1,2],[3,4]])

print(A.shape)

print(C.shape)

np.dot(A,C) # error : A의 열 수(3)과 C의 행 수(2)가 다르다

(2, 3)
(2, 2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
A = np.array([[1,2],[3,4],[5,6]])
print(A.shape)

B = np.array([7,8])
print(B.shape)

np.dot(A,B) # n차원과 1차원 배열을 곱할때도 A의 열 수와 B의 shape를 일치시켜라.

(3, 2)
(2,)


array([23, 53, 83])

In [11]:
# 신경망에서의 행렬 곱 예시
# 편향 b와 활성화 함수를 생략하고 가중치만 가진다고 가정한다.

X = np.array([1,2]) # x1, x2
print(X.shape)

W = np.array([[1,3,5],[2,4,6]]) # [x1->w1,w2,w3], [x2->w1,w2,w3]
print(W)
print(W.shape)

Y = np.dot(X, W) # 입력 * 가중치
print(Y)

(2,)
[[1 3 5]
 [2 4 6]]
(2, 3)
[ 5 11 17]
