In [1]:
# 3층 신경망 구현
# 신경망의 순방향 처리 완성

# A = WX + B

In [7]:
# 0층(입력층)->1층
import numpy as np

X = np.array([1.0,0.5]) # 입력 x1 = 1.0, x2 = 0.5
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]]) # 1층 가중치 w1,w2,w3
B1 = np.array([0.1, 0.2, 0.3]) # 1층 편향 b1, b2 ,b3

print(W1.shape) # (2,3)
print(X.shape) # (2,)
print(B1.shape) # (3,)

A1 = np.dot(X, W1) + B1 # A = X*W + B
print(A1) 

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


In [8]:
# 은닉층에서의 가중치 합(가중 신호와 편향의 총합)을 a로 표기하고, 활성화 함수 h()로 변환된 정보를 z로 표기한다.
# 이 때, 활성화 함수로는 시그모이드 함수를 사용하기로 한다.

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1) # Z = h(A)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [10]:
# 1층->2층

W2 = np.array([[0.1, 0.4], [0.2, 0.5],[0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape) # (3,)
print(W1.shape) # (3,2)
print(B2.shape) # (2,)

A2 = np.dot(Z1, W2) + B2
print(A2)

Z2 = sigmoid(A2)
print(Z2)

(3,)
(2, 3)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [12]:
# 2층 -> 3층(출력층)
# 활성화 함수가 은닉층과 다르다

def identify_function(x): # 출력층의 활성화 함수를 여기서는 항등함수로 구현했음.
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
print(A3)

Y = identify_function(A3) # 혹은 Y = A3
print(Y)

[0.31682708 0.69627909]
[0.31682708 0.69627909]


In [ ]:
# 출력층의 활성화 함수는 풀고자 하는 문제의 성질에 맞게 정한다.
'''
회귀에는 항등 함수를,
2클래스 분류에는 시그모이드 함수를,
다중클래스 분류에는 소프트맥스 함수를 사용하는 것이 일반적이다.
'''

In [16]:
# 지금까지의 구현 정리
# convention : 가중치(W)만 대문자로 쓰고, 편향과 중간 결과 등은 모두 소문자로 쓴다.

# 가중치와 편향을 초기화하는 함수
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.1, 0.2, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

# 신호가 순방향(입력에서 출력 방향)으로 전달됨(순전파)
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identify_function(a3)
    
    return y

network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
print(y)

[0.31611924 0.69472915]


In [ ]:
# 기계학습 문제는 분류classification과 회귀regression으로 나뉜다.
# 분류는 데이터가 어느 클래스에 속하는지 가르는 것이다. ex - 개와 고양이 구별
# 회귀는 입력 데이터에서 연속적인 수치를 예측하는 것이다. ex - 사진 속 인물의 몸무게 추정(57.4kg이라던지)