In [1]:
import numpy as np
x = np.array([1.0,2.0,3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x+y # 배열간의 산술 연산을 수행하고 싶다면 원소의 수가 같아야한다

array([3., 6., 9.])

In [4]:
x*y

array([ 2.,  8., 18.])

In [5]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0 # 넘파이 배열은 이처럼 하나의 수치(스칼라값)과 산술연산도 수행할 수 있다. 이 기능을 브로드캐스트라고 한다. 

array([0.5, 1. , 1.5])

In [8]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [9]:
A.shape # 행렬의 형상(각 차원 크기)

(2, 2)

In [10]:
A.dtype # 행렬에 담긴 원소의 자료형

dtype('int64')

In [11]:
B = np.array([[3, 0],[0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [12]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [13]:
print(A)
A*10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])

In [14]:
# Numpy 배열은 N차원 배열을 작성할 수 있다.
# 수학에서 1차원 배열은 벡터(vector), 2차원 배열은 행렬(matrix)이라고 부른다.
# 벡터와 행렬을 일반화 한 것을 텐서(tensor)라고 부른다.

In [15]:
# numpy에서 형상이 다른 배열끼리 계산하는것을 '브로드캐스트'라고 한다.
A = np.array([[1,2],[3,4]])
B = np.array([10,20]) # A와 곱해지기 위해 B는 ([[10,20],[10,20])으로 자동 확장된다.
A * B

array([[10, 40],
       [30, 80]])

In [19]:
X = np.array(([51, 55], [14,19], [0,4]))
print(X)
X[0] # X의 0행

[[51 55]
 [14 19]
 [ 0  4]]


array([51, 55])

In [20]:
X[0][1] # X의 (0,1) 위치 원소

55

In [21]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [23]:
X = X.flatten() # X를 1차원 배열로 변환(평탄화)
print(X)

[51 55 14 19  0  4]


In [24]:
X[np.array([0,2,4])] # index가 0,2,4인 원소 얻기

array([51, 14,  0])

In [25]:
X>15 # X의 원소중 15가 넘는것에 대해서만 True를 반환하고, 나머지는 False를 반환한다

array([ True,  True, False,  True, False, False])

In [26]:
X[X>15] # X의 원소중 15를 넘는 원소들만 따로 배열로 만들어 반환한다.

array([51, 55, 19])